TYPE=VIEW
query=select `db_receipt_golang_crud_v_2`.`tb_setting_user_grup`.`id` AS `id`,`db_receipt_golang_crud_v_2`.`tb_setting_user`.`id` AS `id_setting_user`,`db_receipt_golang_crud_v_2`.`tb_setting_grup`.`id` AS `id_setting_grup`,`db_receipt_golang_crud_v_2`.`tb_setting_user`.`username` AS `username`,`db_receipt_golang_crud_v_2`.`tb_setting_user`.`full_name` AS `full_name`,`db_receipt_golang_crud_v_2`.`tb_setting_user`.`email` AS `email`,`db_receipt_golang_crud_v_2`.`tb_setting_user`.`image` AS `image`,`db_receipt_golang_crud_v_2`.`tb_setting_grup`.`name_grup` AS `name_grup`,`db_receipt_golang_crud_v_2`.`tb_setting_grup`.`status` AS `STATUS`,`db_receipt_golang_crud_v_2`.`tb_setting_user`.`additional` AS `extension`,`db_receipt_golang_crud_v_2`.`tb_setting_user`.`auth_token` AS `auth_token`,`db_receipt_golang_crud_v_2`.`tb_setting_user`.`password` AS `password` from ((`db_receipt_golang_crud_v_2`.`tb_setting_user_grup` join `db_receipt_golang_crud_v_2`.`tb_setting_grup` on((`db_receipt_golang_crud_v_2`.`tb_setting_grup`.`id` = `db_receipt_golang_crud_v_2`.`tb_setting_user_grup`.`id_setting_grup`))) join `db_receipt_golang_crud_v_2`.`tb_setting_user` on((`db_receipt_golang_crud_v_2`.`tb_setting_user`.`id` = `db_receipt_golang_crud_v_2`.`tb_setting_user_grup`.`id_setting_user`)))
md5=040df0b8b7906ac830a34a3550fa10dd
updatable=1
algorithm=0
definer_user=user
definer_host=%
suid=1
with_check_option=0
timestamp=2020-11-25 11:05:40
create-version=1
source=SELECT\n				tb_setting_user_grup.id AS id,\n				tb_setting_user.id AS id_setting_user,\n				tb_setting_grup.id AS id_setting_grup,\n				tb_setting_user.username AS username,\n				tb_setting_user.full_name AS full_name,\n				tb_setting_user.email AS email,\n				tb_setting_user.image AS image,\n				tb_setting_grup.name_grup AS name_grup,\n				tb_setting_grup.STATUS AS STATUS,\n				tb_setting_user.additional AS extension,\n				tb_setting_user.auth_token AS auth_token,\n				tb_setting_user.password AS password \n			FROM\n				tb_setting_user_grup\n				JOIN tb_setting_grup ON tb_setting_grup.id = tb_setting_user_grup.id_setting_grup\n				JOIN tb_setting_user ON tb_setting_user.id = tb_setting_user_grup.id_setting_user
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `db_receipt_golang_crud_v_2`.`tb_setting_user_grup`.`id` AS `id`,`db_receipt_golang_crud_v_2`.`tb_setting_user`.`id` AS `id_setting_user`,`db_receipt_golang_crud_v_2`.`tb_setting_grup`.`id` AS `id_setting_grup`,`db_receipt_golang_crud_v_2`.`tb_setting_user`.`username` AS `username`,`db_receipt_golang_crud_v_2`.`tb_setting_user`.`full_name` AS `full_name`,`db_receipt_golang_crud_v_2`.`tb_setting_user`.`email` AS `email`,`db_receipt_golang_crud_v_2`.`tb_setting_user`.`image` AS `image`,`db_receipt_golang_crud_v_2`.`tb_setting_grup`.`name_grup` AS `name_grup`,`db_receipt_golang_crud_v_2`.`tb_setting_grup`.`status` AS `STATUS`,`db_receipt_golang_crud_v_2`.`tb_setting_user`.`additional` AS `extension`,`db_receipt_golang_crud_v_2`.`tb_setting_user`.`auth_token` AS `auth_token`,`db_receipt_golang_crud_v_2`.`tb_setting_user`.`password` AS `password` from ((`db_receipt_golang_crud_v_2`.`tb_setting_user_grup` join `db_receipt_golang_crud_v_2`.`tb_setting_grup` on((`db_receipt_golang_crud_v_2`.`tb_setting_grup`.`id` = `db_receipt_golang_crud_v_2`.`tb_setting_user_grup`.`id_setting_grup`))) join `db_receipt_golang_crud_v_2`.`tb_setting_user` on((`db_receipt_golang_crud_v_2`.`tb_setting_user`.`id` = `db_receipt_golang_crud_v_2`.`tb_setting_user_grup`.`id_setting_user`)))
